name: flutter_custom_sliver
description: Flutter Custom Sliver
version: 0.0.1
publisher: jwlee1024@gmail.com
homepage: https://github.com/111coding
repository: https://github.com/111coding/flutter_custom_sliver

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
